// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_unit_matrix
arma::mat generate_unit_matrix(int n, int d);
RcppExport SEXP _GLIM_generate_unit_matrix(SEXP nSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_unit_matrix(n, d));
    return rcpp_result_gen;
END_RCPP
}
// fit_glm_omp_cpp
arma::mat fit_glm_omp_cpp(arma::mat& X, const arma::vec& y, const arma::vec& mle_coefs, const arma::mat& betas, std::string family, int num_threads, int m, bool parallel, bool approx, bool appendix);
RcppExport SEXP _GLIM_fit_glm_omp_cpp(SEXP XSEXP, SEXP ySEXP, SEXP mle_coefsSEXP, SEXP betasSEXP, SEXP familySEXP, SEXP num_threadsSEXP, SEXP mSEXP, SEXP parallelSEXP, SEXP approxSEXP, SEXP appendixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mle_coefs(mle_coefsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type betas(betasSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< bool >::type appendix(appendixSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_glm_omp_cpp(X, y, mle_coefs, betas, family, num_threads, m, parallel, approx, appendix));
    return rcpp_result_gen;
END_RCPP
}
// imvar
arma::vec imvar(arma::mat X, arma::vec y, arma::vec xi, const std::string family, double alpha, const arma::vec& mle, const double mle_val, const arma::mat& J_vectors, const arma::vec& J_values, double dispersion, double tol, double a_val, double b_val, int max_it, bool parallel, int m);
RcppExport SEXP _GLIM_imvar(SEXP XSEXP, SEXP ySEXP, SEXP xiSEXP, SEXP familySEXP, SEXP alphaSEXP, SEXP mleSEXP, SEXP mle_valSEXP, SEXP J_vectorsSEXP, SEXP J_valuesSEXP, SEXP dispersionSEXP, SEXP tolSEXP, SEXP a_valSEXP, SEXP b_valSEXP, SEXP max_itSEXP, SEXP parallelSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mle(mleSEXP);
    Rcpp::traits::input_parameter< const double >::type mle_val(mle_valSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type J_vectors(J_vectorsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type J_values(J_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type a_val(a_valSEXP);
    Rcpp::traits::input_parameter< double >::type b_val(b_valSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(imvar(X, y, xi, family, alpha, mle, mle_val, J_vectors, J_values, dispersion, tol, a_val, b_val, max_it, parallel, m));
    return rcpp_result_gen;
END_RCPP
}
// appendix_code
arma::mat appendix_code(int num_samps, arma::mat X, arma::vec y, arma::vec mle_coefs, arma::mat eig_vecs, arma::vec eig_vals, std::string family, double dispersion, int m, double tol, int max_it, int a_val, int b_val);
RcppExport SEXP _GLIM_appendix_code(SEXP num_sampsSEXP, SEXP XSEXP, SEXP ySEXP, SEXP mle_coefsSEXP, SEXP eig_vecsSEXP, SEXP eig_valsSEXP, SEXP familySEXP, SEXP dispersionSEXP, SEXP mSEXP, SEXP tolSEXP, SEXP max_itSEXP, SEXP a_valSEXP, SEXP b_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_samps(num_sampsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mle_coefs(mle_coefsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eig_vecs(eig_vecsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eig_vals(eig_valsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< int >::type a_val(a_valSEXP);
    Rcpp::traits::input_parameter< int >::type b_val(b_valSEXP);
    rcpp_result_gen = Rcpp::wrap(appendix_code(num_samps, X, y, mle_coefs, eig_vecs, eig_vals, family, dispersion, m, tol, max_it, a_val, b_val));
    return rcpp_result_gen;
END_RCPP
}
// fit_gamma_log_cpp
arma::vec fit_gamma_log_cpp(const arma::mat& X, const arma::mat& XtX, const arma::vec& y, const arma::vec& initial_beta, bool approx);
RcppExport SEXP _GLIM_fit_gamma_log_cpp(SEXP XSEXP, SEXP XtXSEXP, SEXP ySEXP, SEXP initial_betaSEXP, SEXP approxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_beta(initial_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gamma_log_cpp(X, XtX, y, initial_beta, approx));
    return rcpp_result_gen;
END_RCPP
}
// compute_gamma_ll
double compute_gamma_ll(const arma::vec& y, const arma::vec& eta, double shape);
RcppExport SEXP _GLIM_compute_gamma_ll(SEXP ySEXP, SEXP etaSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gamma_ll(y, eta, shape));
    return rcpp_result_gen;
END_RCPP
}
// compute_gamma_ll_mat
arma::vec compute_gamma_ll_mat(const arma::vec& y, const arma::mat& eta, double shape);
RcppExport SEXP _GLIM_compute_gamma_ll_mat(SEXP ySEXP, SEXP etaSEXP, SEXP shapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gamma_ll_mat(y, eta, shape));
    return rcpp_result_gen;
END_RCPP
}
// pearson_estimate_dispersion_gamma
double pearson_estimate_dispersion_gamma(arma::vec y, arma::vec mu_hat, double p);
RcppExport SEXP _GLIM_pearson_estimate_dispersion_gamma(SEXP ySEXP, SEXP mu_hatSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_hat(mu_hatSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(pearson_estimate_dispersion_gamma(y, mu_hat, p));
    return rcpp_result_gen;
END_RCPP
}
// mle_estimate_dispersion_gamma
double mle_estimate_dispersion_gamma(arma::vec y, arma::vec mu_hat, double p);
RcppExport SEXP _GLIM_mle_estimate_dispersion_gamma(SEXP ySEXP, SEXP mu_hatSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_hat(mu_hatSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(mle_estimate_dispersion_gamma(y, mu_hat, p));
    return rcpp_result_gen;
END_RCPP
}
// glm_gamma_pl_cpp
double glm_gamma_pl_cpp(arma::mat& X, const arma::mat& XtX, const arma::vec& y, const arma::vec& mle_coefs, const arma::vec& beta_vals, int m, bool approx, bool appendix);
RcppExport SEXP _GLIM_glm_gamma_pl_cpp(SEXP XSEXP, SEXP XtXSEXP, SEXP ySEXP, SEXP mle_coefsSEXP, SEXP beta_valsSEXP, SEXP mSEXP, SEXP approxSEXP, SEXP appendixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mle_coefs(mle_coefsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vals(beta_valsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< bool >::type appendix(appendixSEXP);
    rcpp_result_gen = Rcpp::wrap(glm_gamma_pl_cpp(X, XtX, y, mle_coefs, beta_vals, m, approx, appendix));
    return rcpp_result_gen;
END_RCPP
}
// fit_gaussian_cpp
arma::vec fit_gaussian_cpp(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _GLIM_fit_gaussian_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gaussian_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// compute_gaussian_ll
double compute_gaussian_ll(const arma::vec& y, const arma::vec& mu, double sigma);
RcppExport SEXP _GLIM_compute_gaussian_ll(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gaussian_ll(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// compute_gaussian_ll_mat
arma::vec compute_gaussian_ll_mat(const arma::vec& y, const arma::mat& mu, double sigma);
RcppExport SEXP _GLIM_compute_gaussian_ll_mat(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gaussian_ll_mat(y, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// est_dispersion
double est_dispersion(const arma::vec& y, const arma::vec& mu, int p);
RcppExport SEXP _GLIM_est_dispersion(SEXP ySEXP, SEXP muSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(est_dispersion(y, mu, p));
    return rcpp_result_gen;
END_RCPP
}
// glm_gaussian_pl_cpp
double glm_gaussian_pl_cpp(const arma::mat& X, const arma::vec& y, const arma::vec& mle_coefs, const arma::vec& beta_vals, int m, bool approx, bool appendix);
RcppExport SEXP _GLIM_glm_gaussian_pl_cpp(SEXP XSEXP, SEXP ySEXP, SEXP mle_coefsSEXP, SEXP beta_valsSEXP, SEXP mSEXP, SEXP approxSEXP, SEXP appendixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mle_coefs(mle_coefsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vals(beta_valsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< bool >::type appendix(appendixSEXP);
    rcpp_result_gen = Rcpp::wrap(glm_gaussian_pl_cpp(X, y, mle_coefs, beta_vals, m, approx, appendix));
    return rcpp_result_gen;
END_RCPP
}
// mle_estimate_dispersion_inv_gauss
double mle_estimate_dispersion_inv_gauss(const arma::vec& y, const double ybar);
RcppExport SEXP _GLIM_mle_estimate_dispersion_inv_gauss(SEXP ySEXP, SEXP ybarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type ybar(ybarSEXP);
    rcpp_result_gen = Rcpp::wrap(mle_estimate_dispersion_inv_gauss(y, ybar));
    return rcpp_result_gen;
END_RCPP
}
// fit_invgauss_cpp
arma::vec fit_invgauss_cpp(const arma::mat& X, const arma::vec& y, const arma::vec& initial_beta, bool approx);
RcppExport SEXP _GLIM_fit_invgauss_cpp(SEXP XSEXP, SEXP ySEXP, SEXP initial_betaSEXP, SEXP approxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_beta(initial_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_invgauss_cpp(X, y, initial_beta, approx));
    return rcpp_result_gen;
END_RCPP
}
// compute_invgauss_ll
double compute_invgauss_ll(const arma::vec& y, const arma::vec& mu, double gamma_val);
RcppExport SEXP _GLIM_compute_invgauss_ll(SEXP ySEXP, SEXP muSEXP, SEXP gamma_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_val(gamma_valSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_invgauss_ll(y, mu, gamma_val));
    return rcpp_result_gen;
END_RCPP
}
// compute_invgauss_ll_mat
arma::vec compute_invgauss_ll_mat(const arma::vec& y, const arma::mat& mu, double gamma_val);
RcppExport SEXP _GLIM_compute_invgauss_ll_mat(SEXP ySEXP, SEXP muSEXP, SEXP gamma_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_val(gamma_valSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_invgauss_ll_mat(y, mu, gamma_val));
    return rcpp_result_gen;
END_RCPP
}
// glm_invgauss_pl_cpp
double glm_invgauss_pl_cpp(const arma::mat& X, const arma::vec& y, const arma::vec& mle_coefs, const arma::vec& beta_vals, int m, bool approx, bool appendix);
RcppExport SEXP _GLIM_glm_invgauss_pl_cpp(SEXP XSEXP, SEXP ySEXP, SEXP mle_coefsSEXP, SEXP beta_valsSEXP, SEXP mSEXP, SEXP approxSEXP, SEXP appendixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mle_coefs(mle_coefsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vals(beta_valsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< bool >::type appendix(appendixSEXP);
    rcpp_result_gen = Rcpp::wrap(glm_invgauss_pl_cpp(X, y, mle_coefs, beta_vals, m, approx, appendix));
    return rcpp_result_gen;
END_RCPP
}
// logistic_ll
double logistic_ll(const arma::mat& X, const arma::vec& y, const arma::vec& beta_vals);
RcppExport SEXP _GLIM_logistic_ll(SEXP XSEXP, SEXP ySEXP, SEXP beta_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_vals(beta_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_ll(X, y, beta_vals));
    return rcpp_result_gen;
END_RCPP
}
// logistic_ll_1d
double logistic_ll_1d(const arma::vec& X, const arma::mat& y, const double beta_vals);
RcppExport SEXP _GLIM_logistic_ll_1d(SEXP XSEXP, SEXP ySEXP, SEXP beta_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type beta_vals(beta_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_ll_1d(X, y, beta_vals));
    return rcpp_result_gen;
END_RCPP
}
// compute_poisson_ll_mat
arma::vec compute_poisson_ll_mat(const arma::mat& eta, const arma::vec y);
RcppExport SEXP _GLIM_compute_poisson_ll_mat(SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(compute_poisson_ll_mat(eta, y));
    return rcpp_result_gen;
END_RCPP
}
// fit_poisson_log_cpp
arma::vec fit_poisson_log_cpp(const arma::mat& X, const arma::vec& y, const arma::vec& initial_beta);
RcppExport SEXP _GLIM_fit_poisson_log_cpp(SEXP XSEXP, SEXP ySEXP, SEXP initial_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial_beta(initial_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_poisson_log_cpp(X, y, initial_beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GLIM_generate_unit_matrix", (DL_FUNC) &_GLIM_generate_unit_matrix, 2},
    {"_GLIM_fit_glm_omp_cpp", (DL_FUNC) &_GLIM_fit_glm_omp_cpp, 10},
    {"_GLIM_imvar", (DL_FUNC) &_GLIM_imvar, 16},
    {"_GLIM_appendix_code", (DL_FUNC) &_GLIM_appendix_code, 13},
    {"_GLIM_fit_gamma_log_cpp", (DL_FUNC) &_GLIM_fit_gamma_log_cpp, 5},
    {"_GLIM_compute_gamma_ll", (DL_FUNC) &_GLIM_compute_gamma_ll, 3},
    {"_GLIM_compute_gamma_ll_mat", (DL_FUNC) &_GLIM_compute_gamma_ll_mat, 3},
    {"_GLIM_pearson_estimate_dispersion_gamma", (DL_FUNC) &_GLIM_pearson_estimate_dispersion_gamma, 3},
    {"_GLIM_mle_estimate_dispersion_gamma", (DL_FUNC) &_GLIM_mle_estimate_dispersion_gamma, 3},
    {"_GLIM_glm_gamma_pl_cpp", (DL_FUNC) &_GLIM_glm_gamma_pl_cpp, 8},
    {"_GLIM_fit_gaussian_cpp", (DL_FUNC) &_GLIM_fit_gaussian_cpp, 2},
    {"_GLIM_compute_gaussian_ll", (DL_FUNC) &_GLIM_compute_gaussian_ll, 3},
    {"_GLIM_compute_gaussian_ll_mat", (DL_FUNC) &_GLIM_compute_gaussian_ll_mat, 3},
    {"_GLIM_est_dispersion", (DL_FUNC) &_GLIM_est_dispersion, 3},
    {"_GLIM_glm_gaussian_pl_cpp", (DL_FUNC) &_GLIM_glm_gaussian_pl_cpp, 7},
    {"_GLIM_mle_estimate_dispersion_inv_gauss", (DL_FUNC) &_GLIM_mle_estimate_dispersion_inv_gauss, 2},
    {"_GLIM_fit_invgauss_cpp", (DL_FUNC) &_GLIM_fit_invgauss_cpp, 4},
    {"_GLIM_compute_invgauss_ll", (DL_FUNC) &_GLIM_compute_invgauss_ll, 3},
    {"_GLIM_compute_invgauss_ll_mat", (DL_FUNC) &_GLIM_compute_invgauss_ll_mat, 3},
    {"_GLIM_glm_invgauss_pl_cpp", (DL_FUNC) &_GLIM_glm_invgauss_pl_cpp, 7},
    {"_GLIM_logistic_ll", (DL_FUNC) &_GLIM_logistic_ll, 3},
    {"_GLIM_logistic_ll_1d", (DL_FUNC) &_GLIM_logistic_ll_1d, 3},
    {"_GLIM_compute_poisson_ll_mat", (DL_FUNC) &_GLIM_compute_poisson_ll_mat, 2},
    {"_GLIM_fit_poisson_log_cpp", (DL_FUNC) &_GLIM_fit_poisson_log_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GLIM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
