# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_unit_matrix <- function(n, d) {
    .Call(`_GLIM_generate_unit_matrix`, n, d)
}

fit_glm_omp_cpp <- function(X, y, mle_coefs, betas, family, num_threads = 1L, m = 1000L, parallel = TRUE, approx = FALSE) {
    .Call(`_GLIM_fit_glm_omp_cpp`, X, y, mle_coefs, betas, family, num_threads, m, parallel, approx)
}

imvar <- function(X, y, xi, family, alpha, mle, mle_val, J_vectors, J_values, dispersion, tol = 1e-2, a_val = 2.0, b_val = 0.65, max_it = 25L, parallel = FALSE) {
    .Call(`_GLIM_imvar`, X, y, xi, family, alpha, mle, mle_val, J_vectors, J_values, dispersion, tol, a_val, b_val, max_it, parallel)
}

appendix_code <- function(eig_vecs, eig_vals, num_samps, X, y, mle_coefs, family, dispersion, m, tol, max_it, a, b) {
    .Call(`_GLIM_appendix_code`, eig_vecs, eig_vals, num_samps, X, y, mle_coefs, family, dispersion, m, tol, max_it, a, b)
}

fit_gamma_log_cpp <- function(X, XtX, y, initial_beta, approx) {
    .Call(`_GLIM_fit_gamma_log_cpp`, X, XtX, y, initial_beta, approx)
}

compute_gamma_ll <- function(y, eta, shape) {
    .Call(`_GLIM_compute_gamma_ll`, y, eta, shape)
}

compute_gamma_ll_mat <- function(y, eta, shape) {
    .Call(`_GLIM_compute_gamma_ll_mat`, y, eta, shape)
}

pearson_estimate_dispersion_gamma <- function(y, mu_hat, p) {
    .Call(`_GLIM_pearson_estimate_dispersion_gamma`, y, mu_hat, p)
}

mle_estimate_dispersion_gamma <- function(y, mu_hat, p) {
    .Call(`_GLIM_mle_estimate_dispersion_gamma`, y, mu_hat, p)
}

glm_gamma_pl_cpp <- function(X, XtX, y, mle_coefs, beta_vals, m, approx) {
    .Call(`_GLIM_glm_gamma_pl_cpp`, X, XtX, y, mle_coefs, beta_vals, m, approx)
}

fit_gaussian_cpp <- function(X, y) {
    .Call(`_GLIM_fit_gaussian_cpp`, X, y)
}

compute_gaussian_ll <- function(y, mu, sigma) {
    .Call(`_GLIM_compute_gaussian_ll`, y, mu, sigma)
}

compute_gaussian_ll_mat <- function(y, mu, sigma) {
    .Call(`_GLIM_compute_gaussian_ll_mat`, y, mu, sigma)
}

est_dispersion <- function(y, mu, p) {
    .Call(`_GLIM_est_dispersion`, y, mu, p)
}

glm_gaussian_pl_cpp <- function(X, y, mle_coefs, beta_vals, m, approx) {
    .Call(`_GLIM_glm_gaussian_pl_cpp`, X, y, mle_coefs, beta_vals, m, approx)
}

mle_estimate_dispersion_inv_gauss <- function(y, ybar) {
    .Call(`_GLIM_mle_estimate_dispersion_inv_gauss`, y, ybar)
}

fit_invgauss_cpp <- function(X, y, initial_beta, approx) {
    .Call(`_GLIM_fit_invgauss_cpp`, X, y, initial_beta, approx)
}

compute_invgauss_ll <- function(y, mu, gamma_val) {
    .Call(`_GLIM_compute_invgauss_ll`, y, mu, gamma_val)
}

compute_invgauss_ll_mat <- function(y, mu, gamma_val) {
    .Call(`_GLIM_compute_invgauss_ll_mat`, y, mu, gamma_val)
}

glm_invgauss_pl_cpp <- function(X, y, mle_coefs, beta_vals, m, approx) {
    .Call(`_GLIM_glm_invgauss_pl_cpp`, X, y, mle_coefs, beta_vals, m, approx)
}

fit_logistic_cpp <- function(X, y, initial_beta, approx) {
    .Call(`_GLIM_fit_logistic_cpp`, X, y, initial_beta, approx)
}

glm_logis_pl_cpp <- function(X, y, mle_coefs, beta_vals, m, approx) {
    .Call(`_GLIM_glm_logis_pl_cpp`, X, y, mle_coefs, beta_vals, m, approx)
}

fit_poisson_log_cpp <- function(X, y) {
    .Call(`_GLIM_fit_poisson_log_cpp`, X, y)
}

compute_poisson_ll <- function(eta, y) {
    .Call(`_GLIM_compute_poisson_ll`, eta, y)
}

compute_poisson_ll_mat <- function(eta, y) {
    .Call(`_GLIM_compute_poisson_ll_mat`, eta, y)
}

glm_poisson_pl_cpp <- function(X, y, mle_coefs, beta_vals, m, approx) {
    .Call(`_GLIM_glm_poisson_pl_cpp`, X, y, mle_coefs, beta_vals, m, approx)
}

